version: '3.8'

services:
  server:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8080:8080"
  nginx:
    depends_on:
      - server
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:80"
